// <auto-generated />
namespace AddCon_TravellingSalesman.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class LatLong : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(LatLong));
        
        string IMigrationMetadata.Id
        {
            get { return "201209111313237_LatLong"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
