// <auto-generated />
namespace AddCon_TravellingSalesman.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class EventTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EventTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201209260804246_Event Table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
